### ISSUE TITLE
Training from scratch

### ISSUE THREAD

**Issue by giovi1** [kkahatapitiya/X3D-Multigrid#11]
Is it possible to train it from scratch? Eventually which is the dataset format I have to provide?

**Comment by kkahatapitiya** [comment]
Yes, Kinetics experiments are trained from scratch. Input clips are provided as RGB frames. You can refer to the dataset file here: https://github.com/kkahatapitiya/X3D-Multigrid/blob/d63d8fe6210d2b38aa26d71b0062b569687d6be2/kinetics.py#L161

**Comment by giovi1** [comment]
Is it possible to use my own dataset to train the network? 
which dataset file I have to refer to? 
Thank you

**Comment by kkahatapitiya** [comment]
Yes, as long as the the dataset is large-enough, you can train form scratch on your data. Otherwise, I would suggest to finetune the K400 pretrained model on your data. Unfortunately, for your own data, you will have to edit the above dataset file yourself. It's straightforward, you can follow how `charades.py` is adopted from `kinetics.py`.

**Comment by giovi1** [comment]
I would try to test the code as it is on the Kinetics dataset, essentially by running `train_x3d_kinetics_multigrid.py`. I have a maximum of 70 GB of storage at my disposal to save the data. Is this sufficient, or is there another way to test the code?
Thank you
